name: Publish Packages

on:
  push:
    branches:
        - main
        - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # pulls all commits (needed for lerna / semantic release to correctly version). https://github.com/actions/checkout/issues/217
        with:
          fetch-depth: "0"
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Setup GIT config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8'

      - name: Install dependencies
        run: npm i

      - name: Authenticate with npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          set -e
          #npm login
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
          npm login --registry=https://registry.npmjs.org --always-auth --//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}
          #npm adduser
          npm whoami

      - name: Release
        run: |
          npx lerna version --conventional-commits --yes && npx lerna publish from-git --yes --loglevel debug
          # npx lerna version --conventional-commits --yes && npx lerna publish from-package --yes
          # npx lerna version --conventional-commits --scope=comp-a

<<<<<<< HEAD
=======
      - name: Publish to Artifactory
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: npm publish --registry https://registry.npmjs.org/
        
        # Replace <YOUR_ARTIFACTORY_REGISTRY> with the URL of your artifactory registry
>>>>>>> main
