name: Build and Publish

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build with webpack
        run: npm run build

      # If you need to configure environment variables for your artifactory, set them here.
      # - name: Set up environment variables
      #   run: |
      #     echo "ARTIFACTORY_USERNAME=your_username" >> $GITHUB_ENV
      #     echo "ARTIFACTORY_PASSWORD=your_password" >> $GITHUB_ENV

      - name: Publish to Artifactory
        run: npm publish --registry <YOUR_ARTIFACTORY_REGISTRY>
        # Replace <YOUR_ARTIFACTORY_REGISTRY> with the URL of your artifactory registry
