name: Publish Packages

on:
  push:
    branches:
        - feat/learna

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8'

      - name: Install dependencies
        run: npm i

      - name: Authenticate with npm
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc 

      - name: Build and Publish headerbykd package
        #if: ${{ github.event_name == 'push' && contains(github.event.commits[0].added, 'packages/headerbykd') }}
        run: npx lerna exec --scope headerbykd -- npm run build && npx lerna exec --scope headerbykd -- npm update
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Build and Publish footerbykd package
        #if: ${{ github.event_name == 'push' && contains(github.event.commits[0].added, 'packages/footerbykd') }}
        run: npx lerna exec --scope footerbykd -- npm run build && npx lerna exec --scope footerbykd -- npm update
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
