name: Publish Packages

on:
  push:
    branches:
        - feat/learna

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        # pulls all commits (needed for lerna / semantic release to correctly version). https://github.com/actions/checkout/issues/217
        with:
          fetch-depth: "0"
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Setup GIT config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.8'

      - name: Install dependencies
        run: npm i

      - name: Authenticate with npm
        env:
            NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          set -e
          npm whoami
          #npm login
          npm login --registry=https://registry.npmjs.org --always-auth --//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc

      #- name: Build and Publish headerbykd package
      #  #if: ${{ github.event_name == 'push' && contains(github.event.commits[0].added, 'packages/headerbykd') }}
      #  run: npx lerna exec --scope headerbykd -- npm run build && npx lerna exec --scope headerbykd -- npm update
      #  env:
      #    NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Release
        run: |
          npx lerna version --conventional-commits --yes && npx lerna publish from-git --yes --no-verify-access --loglevel debug
          # npx lerna version --conventional-commits --yes && npx lerna publish from-package --yes
          # npx lerna version --conventional-commits --scope=comp-a

      # - name: Build and Publish footerbykd package
      #   #if: ${{ github.event_name == 'push' && contains(github.event.commits[0].added, 'packages/footerbykd') }}
      #   run: npx lerna exec --scope footerbykd -- npm run build && npx lerna exec --scope footerbykd -- npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
